#spring.application.name=online_shop
#
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=${DB_DRIVER}

spring:
  application:
    name: online_shop

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

server:
  servlet:
    context-path: ${CONTEXT_PATH}

key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}